# Helm chart values for neon-storage-broker
podLabels:
  neon_env: staging
  neon_service: storage-broker

# Use L4 LB
service:
  # service.annotations -- Annotations to add to the service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external  # use newer AWS Load Balancer Controller
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal  # deploy LB to private subnet
    # assign service to this name at external-dns
    external-dns.alpha.kubernetes.io/hostname: storage-broker-lb.us-west-2.internal.aws.neon.build
  # service.type -- Service type
  type: LoadBalancer
  # service.port -- broker listen port
  port: 50051

ingress:
  enabled: false

metrics:
  enabled: false

settings:
  sentryEnvironment: "staging"
