storage:
  vars:
    bucket_name: pvn-neon-demo-storage-us-west-2
    bucket_region: us-west-2
    console_mgmt_base_url: http://neon-internal-api.aws.neon.build
    broker_endpoint: http://k8s-neonstor-neonstor-0fe36a4e1e-7694288635d4e968.elb.us-west-2.amazonaws.com:50051
    pageserver_config_stub:
      pg_distrib_dir: /usr/local
      metric_collection_endpoint: http://neon-internal-api.aws.neon.build/billing/api/v1/usage_events
      metric_collection_interval: 10min
      tenant_config:
        eviction_policy:
          kind: "LayerAccessThreshold"
          period: "20m"
          threshold: "20m"
      remote_storage:
        bucket_name: "{{ bucket_name }}"
        bucket_region: "{{ bucket_region }}"
        prefix_in_bucket: "pageserver/v1"
    safekeeper_s3_prefix: safekeeper/v1/wal
    hostname_suffix: ""
    remote_user: ssm-user
    ansible_aws_ssm_region: us-west-2
    ansible_aws_ssm_bucket_name: pvn-neon-demo-storage-us-west-2
    console_region_id: aws-us-west-2
    sentry_environment: staging

  children:
    pageservers:
      hosts:
        ec2-18-237-173-164.us-west-2.compute.amazonaws.com:
          ansible_host: i-0db7870a47837f098

    safekeepers:
      hosts:
        ec2-34-221-41-207.us-west-2.compute.amazonaws.com:
          ansible_host: i-0e09cd108279eb4f5
        ec2-34-219-180-253.us-west-2.compute.amazonaws.com:
          ansible_host: i-06083acd29327dce3
        ec2-35-92-31-168.us-west-2.compute.amazonaws.com:
          ansible_host: i-0ba39b03d290c65a3
        ec2-35-91-115-171.us-west-2.compute.amazonaws.com:
          ansible_host: i-0f0929baf23d4127e
